#!/bin/sh
if test "x${NRNHOME}" = "x" ; then
	NRNHOME="/storage/hpc/data/latimerb/miniconda/envs/bmtk_env"
fi
if test "x${NRNBIN}" = "x" ; then
	NRNBIN="/storage/hpc/data/latimerb/miniconda/envs/bmtk_env/bin/"
fi
if test "" = "yes" ; then
	NRNIV="${NRNBIN}nrniv.app/Contents/MacOS/nrniv"
else
	NRNIV="${NRNBIN}nrniv"
fi
"${NRNIV}" -dll "/storage/hpc/data/latimerb/SPWR_BMTK/biophys_components/mechanisms/x86_64/.libs/libnrnmech.so" "$@"
