#!/bin/sh
if test "x${NRNHOME}" = "x" ; then
	NRNHOME="/oasis/scratch/comet/latimerb/temp_project/neuron/nrn"
fi
if test "x${NRNBIN}" = "x" ; then
	NRNBIN="/oasis/scratch/comet/latimerb/temp_project/neuron/nrn/x86_64/bin/"
fi
if test "" = "yes" ; then
	NRNIV="${NRNBIN}nrniv.app/Contents/MacOS/nrniv"
else
	NRNIV="${NRNBIN}nrniv"
fi
"${NRNIV}" -dll "/home/latimerb/SPWR_BMTK/biophys_components/mechanisms/x86_64/.libs/libnrnmech.so" "$@"
